name: gleap_sdk
description: The Gleap SDK for Flutter is the easiest way to integrate Gleap into your apps!
version: 10.0.2
homepage: https://gleap.io

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  js: ^0.6.3
  json_annotation: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  build_runner:
  json_serializable:

flutter:
  plugin:
    platforms:
      android:
        package: io.gleap.gleap_sdk
        pluginClass: GleapSdkPlugin
      ios:
        pluginClass: GleapSdkPlugin
      web:
        pluginClass: GleapSdkWeb
        fileName: gleap_sdk_web.dart
