name: gleap_sdk
description: "Gleap SDK for Flutter: customer support, live chat, in-app bug reporting and customer feedback."
version: 18.1.0
homepage: https://www.gleap.ai

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  json_annotation: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  build_runner:
  json_serializable:

flutter:
  plugin:
    platforms:
      android:
        package: io.gleap.gleap_sdk
        pluginClass: GleapSdkPlugin
      ios:
        pluginClass: GleapSdkPlugin
      web:
        pluginClass: GleapSdkWeb
        fileName: gleap_sdk_web.dart
