// swift-tools-version: 5.9
// The swift-tools-version declares the minimum version of Swift required to build this package.

import PackageDescription

let package = Package(
    name: "gleap_sdk",
    platforms: [
        .iOS("15.0")
    ],
    products: [
        .library(name: "gleap-sdk", targets: ["gleap_sdk"])
    ],
    dependencies: [
        // Generated by the Flutter tool next to the plugin's package (Flutter 3.41+).
        .package(name: "FlutterFramework", path: "../FlutterFramework"),
        // Native Gleap iOS SDK. Bumped together with pubspec.yaml on every release.
        .package(url: "https://github.com/GleapSDK/Gleap-iOS-SDK.git", from: "19.2.1")
    ],
    targets: [
        .target(
            name: "gleap_sdk",
            dependencies: [
                .product(name: "FlutterFramework", package: "FlutterFramework"),
                .product(name: "Gleap", package: "Gleap-iOS-SDK")
            ],
            cSettings: [
                .headerSearchPath("include/gleap_sdk")
            ]
        )
    ]
)
